###
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query { getCourseById(id: -999) {
    id
    name
    instructor {
        id
    }
}}

###
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query { getAllCourses {
    id
    name
}}

###
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

mutation { createCourse(
    request: {
        name: "",
        category: "DEVELOPMENT",
        instructor: {
            name: "Thomas William"
        }
    }) {
    id
    name
}}

###
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

mutation {  deleteCourseById(id : 19)}

###
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query { getInstructorById(id: 2) {
    id
    name
}}

###
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query { getAllInstructors {
    id
    name
}}

###
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

mutation { createInstructor(
    request: {
        name: ""
    }) {
    id
    name
}}

###
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

mutation {  deleteInstructorById(id : 21)}
